import java.util.*;
import java.util.regex.Pattern;
import java.nio.charset.StandardCharsets;
import java.io.*;
import java.util.regex.Matcher;

public class VotacionInterfaz extends javax.swing.JFrame {
    private int dniIngresado;

    /**
     * Creates new form VotacionInterfaz
     */
    public VotacionInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setTitle("PASO");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("");
        jTextField1.setToolTipText("");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setLabelFor(jTextField1);
        jLabel1.setText("INGRESE SU NUMERO DE DOCUMENTO");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Bienvenido al Sistema electoral argentino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
                .createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup().addGap(185, 185, 185).addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup().addGap(237, 237, 237).addComponent(jTextField1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup().addGap(248, 248, 248).addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup().addGap(126, 126, 126).addComponent(jLabel2,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(38, 38, 38)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18).addComponent(jLabel1).addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18).addComponent(jButton1).addContainerGap(169, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        
        dniIngresado = Integer.parseInt(jTextField1.getText()); // Guardar el dni ingresado en una variablez|
        page1Off();
    }

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) { // Si no es integer, tirar error.
            evt.consume();
        }
    }

    public void page1On() {
        jButton1.setEnabled(true);
        jLabel1.setEnabled(true);
        jLabel2.setEnabled(true);
        jTextField1.setEnabled(true);
    }

    public void page1Off() {
        jButton1.setEnabled(false);
        jLabel1.setEnabled(false);
        jLabel2.setEnabled(false);
        jTextField1.setEnabled(false);
    }

    
    public static void main(String args[]) throws IOException {
        BufferedReader br = new BufferedReader(new FileReader("C:\\votos.txt", StandardCharsets.UTF_8));
        // MesaElectoral prueba1 = new MesaElectoral();
        Elector elector1 = new Elector();
        List<Elector> listaElector = new ArrayList<>();

        File archivo = null;
        FileReader fr = null;

        try {
            archivo = new File("C:\\votos.txt");

            String regex = "Nombre:(\\w*\\s?\\w*?).*Apellido:(\\w*).*Domicilio:(.*).*DNI:(\\d*).*cimiento:(\\d*/\\d*/\\d*).*Votacion:(.*)";

            Pattern pattern = Pattern.compile(regex);
            String linea;
            int con = 0;
            while ((linea = br.readLine()) != null) {
                Matcher matcher = pattern.matcher(linea);
                if (matcher.matches()) {
                    System.out.println("NOMBRES :" + matcher.group(1));
                    elector1.setNombre(matcher.group(1));
                    System.out.println("APELLIDOS :" + matcher.group(2));
                    elector1.setApellido(matcher.group(2));
                    System.out.println("DOMICICLIO:" + matcher.group(3));
                    elector1.setDomicilio(new Domicilio(matcher.group(3), null, null, null));
                    System.out.println("DNI:" + matcher.group(4));
                    elector1.setDni(Integer.parseInt(matcher.group(4)));
                    System.out.println("FECHA NACIMIENTO:" + matcher.group(5));
                    elector1.setFecNac(matcher.group(5));
                    System.out.println("Lugar de Votacion:" + matcher.group(6));
                    elector1.setLugVotacion(matcher.group(6));
                }
                // creo que en vez de hacer elector1.setnombre es hacer nombre=matcher.group1 y
                // cuando termina el if(matcher) guardar array.nombre(i)=nombre
                listaElector.add(elector1);
            }

            for (int index = 0; index < listaElector.size(); index++) {
                System.out.println("");
                System.out.println(listaElector.get(index));

            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            // En el finally cerramos el fichero, para asegurarnos
            // que se cierra tanto si todo va bien como si salta
            // una excepcion.
            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotacionInterfaz.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotacionInterfaz.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotacionInterfaz.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotacionInterfaz.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotacionInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration

}